# Site settings
title: Ushahidi Guide
email: bostoncello@gmail.com
description: "Ushahidi documentation for practices and tools around v3 Ushahidi platform"
baseurl: "/guide/"
url: "http://yourdomain.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty

prose:
    rooturl: _posts
    siteurl: http://jcrowley/guide/
    metadata:
        _posts:
          - name: "layout"
            field:
              element: "hidden"
              value: "guide"
          - name: "category"
            field:
              element: "multiselect"
              label: "Category"
              help: "Categorize this post"
              options: 
                  - name: 'Manual'
                    value: 'manual'
                  - name: 'Toolkit'
                    value: 'toolkit'  
                  - name: 'Resource'
                    value: 'resource'         
              placeholder: 'manual'